using Microsoft.WindowsAPICodePack.Dialogs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Path = System.IO.Path;

namespace SglDesigner
{



    public static class SglMapping
    {
        public enum SglType
        {
            Button, Label, Progress, CheckBox,
            Img_Ext, Switch, Arc, Led, Slider, TextBox, Line, Icon, Rectangle, Polygon, MsgBox,
            Circle, Ring, Keyboard, NumberKbd, Dropdown, Barchart, Piechart, Linechart, Box, Bar, Qrcode, Win, Viewlist, Statusbar, Battery, Roller, Unknown
        }
        private static void DeclareEventHandlersRecursive(IEnumerable<SglWidgetData> widgets, StringBuilder sb)
        {
            foreach (var w in widgets)
            {
                // 只有当设置了事件入口名，或者 EventRoutes 字典不为空时才生成
                if (w.IsClickable || w.EventRoutes.Count > 0)
                {
                    string handlerName = string.IsNullOrWhiteSpace(w.EventCallbackName)
                                         ? $"{w.Id}_event_handler"
                                         : w.EventCallbackName;

                    sb.AppendLine($"void {handlerName}(sgl_event_t *event);");
                }

                if (w.Children?.Count > 0)
                    DeclareEventHandlersRecursive(w.Children, sb);
            }
        }
        // 生成 ui.h
        public static string GenerateHeaderFile(List<string> screenNames, IEnumerable<SglResItem> resources, HashSet<string> exportedImages)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("/*This file was generated by SGL UI Designer");
            sb.AppendLine($"SGL UI Designer Version:{Assembly.GetExecutingAssembly().GetName().Version.ToString()}");
            sb.AppendLine($"Project Name:{DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString()}");
            sb.AppendLine("*/");
            sb.AppendLine("");
            sb.AppendLine("#ifndef __UI_H__");
            sb.AppendLine("#define __UI_H__");
            sb.AppendLine("");
            sb.AppendLine("# ifdef __cplusplus");
            sb.AppendLine("extern \"C\" { ");
            sb.AppendLine("#endif");
            sb.AppendLine("#include \"sgl.h\"");
            sb.AppendLine("");

            sb.AppendLine("\ntypedef enum {");
            foreach (var screen in screenNames)
            {

                sb.AppendLine($"    UI_{screen.ToUpper()},");
            }
            sb.AppendLine("}ui_scr_id_t;");

            sb.AppendLine("\ntypedef enum {");
            foreach (var prop in Enum.GetValues(typeof(SglPropertyType)))
            {
                sb.AppendLine($"    {prop.ToString().ToUpper()},");
            }
            sb.AppendLine("}ui_prop_t;");

            sb.AppendLine("\ntypedef enum {");
            foreach (var prop in Enum.GetValues(typeof(SglFlagType)))
            {
                sb.AppendLine($"    {prop.ToString().ToUpper()},");
            }
            sb.AppendLine("}ui_flag_t;");


            sb.AppendLine($"\nextern void ui_init(void);\n");

            // 字体声明
            sb.AppendLine("// --- Fonts ---");
            var fonts = SglResManager.Resources.Where(r => r.ResType == SglResType.FontCSource);
            foreach (var font in fonts)
            {
                sb.AppendLine($"extern const sgl_font_t {font.Name};");
            }
            sb.AppendLine("");

            // 2. 图片声明
            sb.AppendLine("// --- Images ---");
            foreach (var imgVar in exportedImages)
            {
                // 注意：如果之前根据类型分了 pixmap 和 icon_pixmap，这里要对应处理
                // 假设图标用 sgl_icon_pixmap_t，普通图片用 sgl_pixmap_t
                if (imgVar.StartsWith("ico_"))
                    sb.AppendLine($"extern const sgl_icon_pixmap_t {imgVar.Substring(4)}_pixmap;");
                else
                    sb.AppendLine($"extern const sgl_pixmap_t {imgVar.Substring(4)}_pixmap;");
            }
            sb.AppendLine("");

            //  核心修改：所有控件 ID 声明 (Extern Objects)
            //  控件 ID 声明 (使用 HashSet 去重)
            sb.AppendLine("// --- Widget Identifiers ---");
            HashSet<string> declaredIds = new HashSet<string>();

            foreach (var screen in SglScreen.Instance.ScreenList)
            {
                sb.AppendLine($"// Widgets in {screen.Id}");

                // 只有没声明过才进行 extern 声明
                if (!declaredIds.Contains(screen.Id))
                {
                    sb.AppendLine($"extern sgl_obj_t* {screen.Id};");
                    declaredIds.Add(screen.Id);
                }

                // 递归处理子控件，同时传递 HashSet
                DeclareAllWidgetsRecursive(screen.Widgets, sb, declaredIds);
                sb.AppendLine("");
            }

            //  初始化函数声明
            sb.AppendLine("// --- Init Functions ---");
            foreach (var name in screenNames)
            {
                sb.AppendLine($"extern sgl_obj_t* ui_{name}_init(void);");
            }

            //  事件路由声明
            sb.AppendLine("\n// --- Event Handler Routes ---");
            foreach (var screen in SglScreen.Instance.ScreenList)
            {
                DeclareEventHandlersRecursive(screen.Widgets, sb);
            }

            sb.AppendLine("");
            sb.AppendLine("#ifdef __cplusplus");
            sb.AppendLine("} /*extern \"C\"*/");
            sb.AppendLine("#endif");
            sb.AppendLine("");
            sb.AppendLine("#endif");
            return sb.ToString();
        }
        // 生成 ui.h
        public static string GenerateDefineFile(List<string> screenNames, IEnumerable<SglResItem> resources, HashSet<string> exportedImages)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("/*\nThis file was generated by SGL UI Designer");
            sb.AppendLine($"SGL UI Designer Version:{Assembly.GetExecutingAssembly().GetName().Version.ToString()}");
            sb.AppendLine($"Project Date:{DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString()}");
            sb.AppendLine("*/");
            sb.AppendLine("");
            sb.AppendLine("#include \"sgl.h\"");
            sb.AppendLine("#include \"ui.h\"");
            sb.AppendLine("");

            //  核心修改：所有控件 ID 声明 (Extern Objects)
            //  控件 ID 声明 (使用 HashSet 去重)
            sb.AppendLine("// --- object define ---");
            HashSet<string> declaredIds = new HashSet<string>();

            foreach (var screen in SglScreen.Instance.ScreenList)
            {
                sb.AppendLine($"// object in {screen.Id}");

                // 只有没声明过才进行 extern 声明
                if (!declaredIds.Contains(screen.Id))
                {
                    sb.AppendLine($"sgl_obj_t* {screen.Id} = NULL;");
                    declaredIds.Add(screen.Id);
                }

                // 递归处理子控件，同时传递 HashSet
                DeclareAllWidgetsRecursive2(screen.Widgets, sb, declaredIds);
                sb.AppendLine("");
            }

            sb.AppendLine("// --- Global Entry ---");
            sb.AppendLine($"\nvoid ui_screen_load(ui_scr_id_t id);\n");
            sb.AppendLine($"void ui_init(void)");
            sb.AppendLine("{\n");
            sb.AppendLine($"    ui_screen_load(UI_{screenNames[0].ToUpper()});");
            foreach (var name in screenNames)
            {
                sb.AppendLine($"    //ui_{name}_init();");
            }
            sb.AppendLine("}\n");
            sb.AppendLine("");
            return sb.ToString();
        }
        public static string GenerateHelperFile(List<string> screenNames, IEnumerable<SglResItem> resources, HashSet<string> exportedImages)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("/*\nThis file was generated by SGL UI Designer");
            sb.AppendLine($"SGL UI Designer Version:{Assembly.GetExecutingAssembly().GetName().Version.ToString()}");
            sb.AppendLine($"Project Date:{DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString()}");
            sb.AppendLine("*/");
            sb.AppendLine("");
            sb.AppendLine("#include \"sgl.h\"");
            sb.AppendLine("#include \"ui.h\"");
            sb.AppendLine("");


            sb.AppendLine("// --- Helper ---");
            sb.AppendLine("\n");

            sb.AppendLine("typedef struct{");
            sb.AppendLine("     ui_scr_id_t id;");
            sb.AppendLine("     sgl_obj_t * (*page_init) (void);");
            sb.AppendLine("}ui_page_t;");
            sb.AppendLine("\nui_page_t ui_pages[] = {");
            foreach (var screen in screenNames)
            {

                sb.AppendLine("     {" + $"UI_{screen.ToUpper()},ui_{screen}_init" + "},");
            }
            sb.AppendLine("};\n");

            sb.AppendLine($"void ui_screen_load(ui_scr_id_t id)");
            sb.AppendLine("{");
            sb.AppendLine("     sgl_obj_t* new_page = ui_pages[id].page_init();");
            sb.AppendLine("     sgl_screen_load(new_page);");
            sb.AppendLine("     //删除之前的页面,节约内存");
            sb.AppendLine("     sgl_obj_t* current_page = sgl_screen_act();");
            sb.AppendLine("     if (current_page != NULL && current_page != new_page) {\r\n        sgl_obj_delete(current_page);\r\n    }");
            sb.AppendLine("}\n");
            sb.AppendLine($"//设置基本属性");
            sb.AppendLine($"void ui_obj_set_property(sgl_obj_t* obj,  ui_prop_t type, int value)");
            sb.AppendLine("{");
            sb.AppendLine("     switch(type)");
            sb.AppendLine("     {");
            sb.AppendLine("         case BASIC_X:sgl_obj_set_pos_x(obj, value);break;");
            sb.AppendLine("         case BASIC_Y:sgl_obj_set_pos_y(obj, value);break;");
            sb.AppendLine("         case BASIC_WIDTH:sgl_obj_set_width(obj, value);break;");
            sb.AppendLine("         case BASIC_HEIGHT:sgl_obj_set_height(obj, value);break;");
            sb.AppendLine("         case BORDER_WIDTH:sgl_obj_set_border_width(obj, value);break;");
            sb.AppendLine("         case BORDER_RADIUS:sgl_obj_set_radius(obj, value);break;");
            sb.AppendLine("         default:break;");
            sb.AppendLine("     }");
            sb.AppendLine("}\n");
            sb.AppendLine($"//设置交互属性");
            sb.AppendLine($"void ui_obj_set_flag(sgl_obj_t* obj,  ui_flag_t type)");
            sb.AppendLine("{");
            sb.AppendLine("     switch(type)");
            sb.AppendLine("     {");
            sb.AppendLine("         case HIDDEN:sgl_obj_set_hidden(obj);break;");
            sb.AppendLine("         case VISABLE:sgl_obj_set_visible(obj);break;");
            sb.AppendLine("         case CLICKABLE:sgl_obj_set_clickable(obj);break;");
            sb.AppendLine("         case MOVABLE:sgl_obj_set_movable(obj);break;");
            sb.AppendLine("         case UNMOVABLE:sgl_obj_set_unmovable(obj);break;");
            sb.AppendLine("         case FLEXIBLE:sgl_obj_set_flexible(obj);break;");
            sb.AppendLine("         case UNFLEXIBLE:sgl_obj_set_unflexible(obj);break;");
            sb.AppendLine("         case MOVE_TOP:sgl_obj_move_top(obj);break;");
            sb.AppendLine("         case MOVE_UP:sgl_obj_move_up(obj);break;");
            sb.AppendLine("         case MOVE_BOTTOM:sgl_obj_move_bottom(obj);break;");
            sb.AppendLine("         case MOVE_DOWN:sgl_obj_move_down(obj);break;");
            sb.AppendLine("         default:break;");
            sb.AppendLine("     }");
            sb.AppendLine("}\n");
            sb.AppendLine("");
            return sb.ToString();
        }
        private static void DeclareAllWidgetsRecursive(IEnumerable<SglWidgetData> widgets, StringBuilder sb, HashSet<string> declaredIds)
        {
            if (widgets == null) return;

            foreach (var widget in widgets)
            {
                // 检查是否已经声明过（防止重复声明屏幕 ID 或同名控件）
                if (!string.IsNullOrEmpty(widget.Id) && !declaredIds.Contains(widget.Id))
                {
                    sb.AppendLine($"extern sgl_obj_t* {widget.Id};");
                    declaredIds.Add(widget.Id);
                }

                if (widget.Children != null && widget.Children.Count > 0)
                {
                    DeclareAllWidgetsRecursive(widget.Children, sb, declaredIds);
                }
            }
        }
        private static void DeclareAllWidgetsRecursive2(IEnumerable<SglWidgetData> widgets, StringBuilder sb, HashSet<string> declaredIds)
        {
            if (widgets == null) return;

            foreach (var widget in widgets)
            {
                // 检查是否已经声明过（防止重复声明屏幕 ID 或同名控件）
                if (!string.IsNullOrEmpty(widget.Id) && !declaredIds.Contains(widget.Id))
                {
                    sb.AppendLine($"sgl_obj_t* {widget.Id} = NULL;");
                    declaredIds.Add(widget.Id);
                }

                if (widget.Children != null && widget.Children.Count > 0)
                {
                    DeclareAllWidgetsRecursive2(widget.Children, sb, declaredIds);
                }
            }
        }

        // 专门用于递归导出全局变量的方法
        private static void GenerateGlobalVariables(SglWidgetData widget, StringBuilder sbVars)
        {
            if (widget is SglBarchartData chart)
            {
                string labelVarName = $"{chart.Tag}_labels";
                string valueVarName = $"{chart.Tag}_values";

                // 导出 X 轴标签数组 (数量随 chart.XLabelCount 变化)
                var labels = Enumerable.Range(0, chart.XLabelCount)
                                       .Select(i => $"\"{(char)('A' + i % 26)}\"");
                sbVars.AppendLine($"const char* {labelVarName}[] = {{ {string.Join(", ", labels)} }};");

                // 2. 导出数值数组 (基于当前的 YMax/YMin 计算预览值)
                var values = Enumerable.Range(0, chart.XLabelCount)
                    .Select(i =>
                    {
                        double percent = 0.3 + (i * 0.15) % 0.6;
                        return (int)(chart.YMin + (chart.YMax - chart.YMin) * percent);
                    });
                sbVars.AppendLine($"int32_t {valueVarName}[] = {{ {string.Join(", ", values)} }};");
                sbVars.AppendLine();
            }
            else if (widget is SglLinechartData linechart)
            {
                string labelVarName = $"{linechart.Tag}_labels";
                string valueVarName = $"{linechart.Tag}_pts";
                IEnumerable<int> values = (linechart.Values != null && linechart.Values.Count > 0)
                    ? linechart.Values
                    : new[] { 0 };
                var labels = values.Select((v, i) => $"\"{i}\"");

                sbVars.AppendLine($"const char* {labelVarName}[] = {{ {string.Join(", ", labels)} }};");
                sbVars.AppendLine($"int32_t {valueVarName}[] = {{ {string.Join(", ", values)} }};");
                sbVars.AppendLine();
            }
            // 递归子节点
            foreach (var child in widget.Children) GenerateGlobalVariables(child, sbVars);
        }
        // 生成单个屏幕的 C 代码
        public static string ConvertPageToCode(SglPageData page)
        {
            StringBuilder sbVars = new StringBuilder(); // 全局变量区
            StringBuilder sb = new StringBuilder();

            //sb.AppendLine($"sgl_obj_t* {page.Id}; // 全局句柄\n");
            sbVars.AppendLine($"#include \"ui.h\"\n");
            // 找到根容器
            var root = page.Widgets.FirstOrDefault(w => w.Parent == null);
            if (root != null)
            {
                // 强制给根容器分配 Tag，确保和页面 ID 一致
                root.Tag = page.Id;

                // --- 1. 使用递归扫描所有控件，生成全局变量定义 ---
                GenerateGlobalVariables(root, sbVars);

                // 导出全局变量

                sb.AppendLine($"sgl_obj_t* ui_{page.Id}_init(void) {{");

                // 2. 生成根容器代码
                // 注意：这里手动处理第一行，不带类型声明，直接赋值给全局变量
                sb.AppendLine($"    // --- {page.Id} ---");
                sb.AppendLine($"    {page.Id} = sgl_rect_create(NULL);"); // 去掉 sgl_obj_t*

                var scr = root as SglPanelData;

                //  生成根容器的其他属性 (SetSize, SetPos 等)
                // 可以稍微修改 GenerateSglCode，或者在这里手动拼剩下的
                sb.AppendLine($"    sgl_obj_set_size({page.Id}, {root.W}, {root.H});");
                sb.AppendLine($"    sgl_obj_set_pos({page.Id}, {root.X}, {root.Y});");
                //sb.AppendLine($"//    sgl_obj_set_border_width({page.Id},{scr.BorderWidth});");
                //sb.AppendLine($"//    sgl_obj_set_border_Color({page.Id},{scr.BorderColor});");
                sb.AppendLine($"    sgl_rect_set_color({page.Id}, {sgl_rgb(scr.BgColor)});");
                sb.AppendLine($"    sgl_rect_set_alpha({page.Id}, {scr.Opacity});");
                sb.AppendLine($"    sgl_rect_set_radius({page.Id}, {scr.Radius});");
                sb.AppendLine($"    sgl_rect_set_border_width({page.Id}, {scr.BorderWidth});");
                sb.AppendLine($"    sgl_rect_set_border_color({page.Id}, {sgl_rgb(scr.BorderColor)});");
                // 2. 设置图像资源 (pixmap)
                if (!string.IsNullOrEmpty(scr.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_rect_set_pixmap({scr.Id}, &{scr.Id}_{scr.PixmapVarName}_pixmap);");
                }
                // 2. 遍历子控件，此时 parentName 传入 page.Id
                //  递归生成子控件
                if (root.Children.Count > 0)
                {
                    sb.AppendLine($"    // Children of {page.Id}");
                    foreach (var child in root.Children)
                    {
                        // 传入根容器的变量名作为父节点
                        sb.Append(SglMapping.GenerateSglCode(child, page.Id));
                    }
                }
            }

            sb.AppendLine($"\n  return {page.Id};");
            sb.AppendLine("}");
            return sbVars.ToString() + "\n" + sb.ToString();
        }


        public static string GenerateSglCode(SglWidgetData d, string parentName = "screen")
        {
            StringBuilder sb = new StringBuilder();
            string name = d.Id;
            string type = d.Type.ToString().ToLower();

            sb.AppendLine($"    // --- {name} ---");

            // 创建对象，使用传入的 parentName
            if (d is SglBoxData)
            {
                sb.AppendLine($"    {name} = sgl_box_create({parentName});");
            }
            else if (d is SglPanelData || d.Type == SglMapping.SglType.Rectangle)
            {
                sb.AppendLine($"    {name} = sgl_rect_create({parentName});");
            }
            else
            {
                sb.AppendLine($"    {name} = sgl_{type}_create({parentName});");
            }
            sb.AppendLine($"    sgl_obj_set_size({name}, {d.W}, {d.H});");
            sb.AppendLine($"    sgl_obj_set_pos({name}, {d.X}, {d.Y});");
            if(d.IsHidden)
            {
                sb.AppendLine($"    sgl_obj_set_hidden({name});");
            }
            if (d is SglButtonData btn)
            {
                // 映射 sgl_button_set_color (主体色)
                sb.AppendLine($"    sgl_button_set_color({name}, {sgl_rgb(btn.BgColor)});");

                // 映射 sgl_button_set_text
                sb.AppendLine($"    sgl_button_set_text({name}, \"{btn.Text}\");");

                sb.AppendLine($"    sgl_button_set_font({name}, &{btn.FontName});");

                // 映射 sgl_button_set_text_color
                sb.AppendLine($"    sgl_button_set_text_color({name}, {sgl_rgb(btn.TextColor)});");

                // 映射 sgl_button_set_alpha
                sb.AppendLine($"    sgl_button_set_alpha({name}, {btn.Opacity});");

                // 映射 sgl_button_set_radius (调用底层 sgl_obj_set_radius)
                if (btn.Radius > 0)
                    sb.AppendLine($"    sgl_button_set_radius({name}, {btn.Radius});");

                // 映射 sgl_button_set_border (如果有宽度)
                if (btn.BorderWidth > 0)
                {
                    sb.AppendLine($"    sgl_button_set_border_width({name}, {btn.BorderWidth});");
                    sb.AppendLine($"    sgl_button_set_border_color({name}, {sgl_rgb(btn.BorderColor)});");
                }



            }
            else if (d is SglLabelData lbl)
            {
                sb.AppendLine($"    sgl_label_set_text({name}, \"{lbl.Text}\");");
                sb.AppendLine($"    sgl_label_set_font({name}, &{lbl.FontName});");
                sb.AppendLine($"    sgl_label_set_text_color({name}, {sgl_rgb(lbl.TextColor)});");

                if (lbl.BgColor.A > 0)
                {
                    sb.AppendLine($"    sgl_label_set_bg_color({name}, {sgl_rgb(lbl.BgColor)});");
                }


                sb.AppendLine($"    sgl_label_set_text_align({name}, {GetAlignEnumName(lbl.TextAlign)});");
                sb.AppendLine($"    sgl_label_set_alpha({name}, {lbl.Opacity});");

                if (lbl.TextRotation != 0)
                    sb.AppendLine($"    sgl_label_set_text_rotation({name}, {lbl.TextRotation});");

                if (lbl.OffsetX != 0 || lbl.OffsetY != 0)
                    sb.AppendLine($"    sgl_label_set_text_offset({name}, {lbl.OffsetX}, {lbl.OffsetY});");

                if (lbl.Radius > 0)
                    sb.AppendLine($"    sgl_label_set_radius({name}, {lbl.Radius});");
            }
            else if (d is SglBarData bar)
            {
                if (bar.IsVertical)
                {
                    sb.AppendLine($"    sgl_obj_set_size({name}, {bar.H}, {bar.W});");
                }
                sb.AppendLine($"    sgl_bar_set_value({name}, {bar.Value});");
                sb.AppendLine($"    sgl_bar_set_fill_color({name}, {sgl_rgb(bar.FillColor)});");
                //sb.AppendLine($"    sgl_bar_set_fill_alpha({name}, {bar.Opacity});");
                sb.AppendLine($"    sgl_bar_set_track_color({name}, {sgl_rgb(bar.TrackColor)});");
                //sb.AppendLine($"    sgl_bar_set_track_alpha({name}, {bar.Opacity});");
                sb.AppendLine($"    sgl_bar_set_direct({name}, {(bar.IsVertical ? 1 : 0)});");
                sb.AppendLine($"    sgl_bar_set_radius({name}, {bar.Radius});");
                sb.AppendLine($"    sgl_bar_set_border_width({name}, {bar.BorderWidth});");
                sb.AppendLine($"    sgl_bar_set_border_color({name}, {sgl_rgb(bar.BorderColor)});");

                if (!string.IsNullOrEmpty(bar.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_bar_set_pixmap({name}, &{bar.Id}_{bar.PixmapVarName}_pixmap);");
                }
            }
            else if (d is SglProgressData prog)
            {
                sb.AppendLine($"    sgl_progress_set_value({name}, {prog.Value});");
                sb.AppendLine($"    sgl_progress_set_fill_color({name}, {sgl_rgb(prog.FillColor)});");
                sb.AppendLine($"    sgl_progress_set_fill_alpha({name}, {prog.FillAlpha});");
                sb.AppendLine($"    sgl_progress_set_track_color({name}, {sgl_rgb(prog.TrackColor)});");
                sb.AppendLine($"    sgl_progress_set_track_alpha({name}, {prog.TrackAlpha});");
                sb.AppendLine($"    sgl_progress_set_radius({name}, {prog.Radius});");
                sb.AppendLine($"    sgl_progress_set_border_width({name}, {prog.BorderWidth});");
                sb.AppendLine($"    sgl_progress_set_border_color({name}, {sgl_rgb(prog.BorderColor)});");

                sb.AppendLine($"    sgl_progress_set_fill_gap({name}, {prog.FillGap});");
                sb.AppendLine($"    sgl_progress_set_fill_radius({name}, {prog.FillRadius});");
                sb.AppendLine($"    sgl_progress_set_fill_width({name}, {prog.FillWidth});");
            }
            else if (d is SglSwitchData sw)
            {
                sb.AppendLine($"    sgl_switch_set_status({name}, {(sw.Status ? "true" : "false")});");
                sb.AppendLine($"    sgl_switch_set_color({name}, {sgl_rgb(sw.ActiveColor)});");
                sb.AppendLine($"    sgl_switch_set_bg_color({name}, {sgl_rgb(sw.InactiveColor)});");
                sb.AppendLine($"    sgl_switch_set_knob_color({name}, {sgl_rgb(sw.KnobColor)});");
                sb.AppendLine($"    sgl_switch_set_knob_radius({name}, {sw.KnobRadius});");
                sb.AppendLine($"    sgl_switch_set_knob_margin({name}, {sw.KnobMargin});");
                sb.AppendLine($"    sgl_switch_set_radius({name}, {sw.Radius});");
                sb.AppendLine($"    sgl_switch_set_border_width({name}, {sw.BorderWidth});");
                sb.AppendLine($"    sgl_switch_set_border_color({name}, {sgl_rgb(sw.BorderColor)});");
            }
            else if (d is SglCheckboxData cb)
            {
                sb.AppendLine($"    sgl_checkbox_set_status({name}, {(cb.Status ? "true" : "false")});");
                sb.AppendLine($"    sgl_checkbox_set_text({name}, \"{cb.Text}\");");
                sb.AppendLine($"    sgl_checkbox_set_font({name}, &{cb.FontName});");
                sb.AppendLine($"    sgl_checkbox_set_color({name}, {sgl_rgb(cb.TextColor)});");
                sb.AppendLine($"    sgl_checkbox_set_alpha({name}, {cb.Alpha});");
            }
            else if (d is SglLedData led)
            {
                sb.AppendLine($"    sgl_led_set_radius({name}, {led.Radius});");
                sb.AppendLine($"    sgl_led_set_on_color({name}, {sgl_rgb(led.OnColor)});");
                sb.AppendLine($"    sgl_led_set_off_color({name}, {sgl_rgb(led.OffColor)});");
                sb.AppendLine($"    sgl_led_set_bg_color({name}, {sgl_rgb(led.BgColor)});");
                sb.AppendLine($"    sgl_led_set_status({name}, {(led.Status ? "true" : "false")});");
            }
            else if (d is SglArcData arc)
            {
                sb.AppendLine($"    sgl_arc_set_color({name}, {sgl_rgb(arc.ArcColor)});");
                sb.AppendLine($"    sgl_arc_set_radius({name}, {arc.RadiusIn}, {arc.RadiusOut});");
                sb.AppendLine($"    sgl_arc_set_start_angle({name}, {arc.StartAngle});");
                sb.AppendLine($"    sgl_arc_set_end_angle({name}, {arc.EndAngle});");
                sb.AppendLine($"    sgl_arc_set_alpha({name}, {arc.Opacity});");
            }
            else if (d is SglSliderData sl)
            {
                sb.AppendLine($"    sgl_slider_set_value({name}, {sl.Value});");
                sb.AppendLine($"    sgl_slider_set_thickness({name}, {sl.Thickness});");
                //如果是垂直 交换宽高
                if (sl.IsVertical)
                {
                    sb.AppendLine($"    sgl_obj_set_size({name}, {sl.H}, {sl.W});");

                }
                sb.AppendLine($"    sgl_slider_set_direct({name}, {(sl.IsVertical ? 1 : 0)});");
                sb.AppendLine($"    sgl_slider_set_radius({name}, {sl.Radius});");
                sb.AppendLine($"    sgl_slider_set_track_color({name}, {sgl_rgb(sl.TrackColor)});");
                sb.AppendLine($"    sgl_slider_set_fill_color({name}, {sgl_rgb(sl.FillColor)});");
                sb.AppendLine($"    sgl_slider_set_knob_color({name}, {sgl_rgb(sl.KnobColor)});");

            }
            else if (d is SglTextBoxData tb)
            {
                sb.AppendLine($"    sgl_textbox_set_text({name}, \"{tb.Text}\");");
                sb.AppendLine($"    sgl_textbox_set_text_color({name}, {sgl_rgb(tb.TextColor)});");
                sb.AppendLine($"    sgl_textbox_set_bg_color({name}, {sgl_rgb(tb.BgColor)});");
                sb.AppendLine($"    sgl_textbox_set_border_color({name}, {sgl_rgb(tb.BorderColor)});");
                sb.AppendLine($"    sgl_textbox_set_border_width({name}, {tb.BorderWidth});");
                sb.AppendLine($"    sgl_textbox_set_radius({name}, {tb.Radius});");
                sb.AppendLine($"    sgl_textbox_set_line_margin({name}, {tb.LineMargin});");
                sb.AppendLine($"    sgl_textbox_set_text_font({name}, &{tb.FontName});");
            }
            else if (d is SglPolygonData pg)
            {
                // 生成唯一的顶点数组名称，防止冲突
                string pointsArrayName = $"{name}_pts";

                // 2. 在初始化代码上方或当前块生成静态数组 (注意：根据的生成器架构，数组定义可能需要放在函数开头或静态区)
                sb.AppendLine($"    static sgl_pos_t {pointsArrayName}[] = {{");
                foreach (var pt in pg.Vertices)
                {
                    // 强制转为整型，匹配 sgl_pos_t 的 int16_t 类型
                    sb.AppendLine($"        {{{(int)pt.X}, {(int)pt.Y}}},");
                }
                sb.AppendLine("    };");

                //  调用 SGL 多边形设置接口
                sb.AppendLine($"    sgl_polygon_set_vertices({name}, {pointsArrayName}, {pg.Vertices.Count});");
                sb.AppendLine($"    sgl_polygon_set_fill_color({name}, {sgl_rgb(pg.FillColor)});");
                sb.AppendLine($"    sgl_polygon_set_border_color({name}, {sgl_rgb(pg.PolygonBorderColor)});");
                sb.AppendLine($"    sgl_polygon_set_border_width({name}, {pg.PolygonBorderWidth});");
                sb.AppendLine($"    sgl_polygon_set_alpha({name}, {pg.Opacity});");

                //  处理文本与字体
                if (!string.IsNullOrEmpty(pg.Text))
                {
                    sb.AppendLine($"    sgl_polygon_set_text({name}, \"{pg.Text}\");");
                    sb.AppendLine($"    sgl_polygon_set_text_color({name}, {sgl_rgb(pg.TextColor)});");
                    // 如果 PolygonData 中也存了 FontName
                    if (!string.IsNullOrEmpty(pg.FontName))
                    {
                        sb.AppendLine($"    sgl_polygon_set_font({name}, &{pg.FontName});");
                    }
                }
            }
            else if (d is SglMsgBoxData mb)
            {
                // 基础属性
                sb.AppendLine($"    sgl_msgbox_set_title_text({name}, \"{mb.TitleText}\");");
                sb.AppendLine($"    sgl_msgbox_set_title_text_color({name}, {sgl_rgb(mb.TitleColor)});");
                sb.AppendLine($"    sgl_msgbox_set_title_height({name}, {mb.TitleHeight});");

                sb.AppendLine($"    sgl_msgbox_set_msg_text({name}, \"{mb.MsgText.Replace("\n", "\\n")}\");");
                sb.AppendLine($"    sgl_msgbox_set_msg_text_color({name}, {sgl_rgb(mb.MsgColor)});");
                sb.AppendLine($"    sgl_msgbox_set_msg_line_margin({name}, {mb.MsgLineMargin});");

                // 按钮设置
                sb.AppendLine($"    sgl_msgbox_set_left_btn_text({name}, \"{mb.LeftBtnText}\");");
                sb.AppendLine($"    sgl_msgbox_set_left_btn_color({name}, {sgl_rgb(mb.LbtnColor)});");
                sb.AppendLine($"    sgl_msgbox_set_left_btn_text_color({name}, {sgl_rgb(mb.LbtnTextColor)});");

                sb.AppendLine($"    sgl_msgbox_set_right_btn_text({name}, \"{mb.RightBtnText}\");");
                sb.AppendLine($"    sgl_msgbox_set_right_btn_color({name}, {sgl_rgb(mb.RbtnColor)});");
                sb.AppendLine($"    sgl_msgbox_set_right_btn_text_color({name}, {sgl_rgb(mb.RbtnTextColor)});");

                // 窗体样式
                sb.AppendLine($"    sgl_msgbox_set_color({name}, {sgl_rgb(mb.BgColor)});");
                sb.AppendLine($"    sgl_msgbox_set_border_color({name}, {sgl_rgb(mb.BorderColor)});");
                sb.AppendLine($"    sgl_msgbox_set_border_width({name}, {mb.BorderWidth});");
                sb.AppendLine($"    sgl_msgbox_set_alpha({name}, {mb.Opacity});");
                sb.AppendLine($"    sgl_msgbox_set_radius({name}, {mb.Radius});");

                if (!string.IsNullOrEmpty(mb.FontName))
                    sb.AppendLine($"    sgl_msgbox_set_font({name}, &{mb.FontName});");
            }
            else if (d is SglWinData win)
            {
                // 标题
                sb.AppendLine($"    sgl_win_set_title_text({name}, \"{win.TitleText}\");");
                sb.AppendLine($"    sgl_win_set_title_text_color({name}, {sgl_rgb(win.TitleTextColor)});");
                sb.AppendLine($"    sgl_win_set_title_bg_color({name}, {sgl_rgb(win.TitleBgColor)});");
                sb.AppendLine($"    sgl_win_set_title_height({name}, {win.TitleHeight});");
                sb.AppendLine($"    sgl_win_set_title_text_align({name}, {win.TitleAlign});");

                // 关闭按钮
                sb.AppendLine($"    sgl_win_set_close_btn_color({name}, {sgl_rgb(win.CloseColor)});");

                // 外观
                sb.AppendLine($"    sgl_win_set_color({name}, {sgl_rgb(win.BgColor)});");
                sb.AppendLine($"    sgl_win_set_border_color({name}, {sgl_rgb(win.BorderColor)});");
                sb.AppendLine($"    sgl_win_set_border_width({name}, {win.BorderWidth});");
                sb.AppendLine($"    sgl_win_set_alpha({name}, {win.Opacity});");
                sb.AppendLine($"    sgl_win_set_radius({name}, {win.Radius});");

                if (!string.IsNullOrEmpty(win.FontName))
                    sb.AppendLine($"    sgl_win_set_title_font({name}, &{win.FontName});");

                if (win.Children != null && win.Children.Count > 0)
                {
                    sb.AppendLine($"    // Children of {name}");
                    foreach (var child in win.Children)
                        sb.Append(GenerateSglCode(child, name));
                }
            }
            else if (d is SglViewlistData vl)
            {
                sb.AppendLine($"    sgl_viewlist_set_bg_color({name}, {sgl_rgb(vl.BgColor)});");
                sb.AppendLine($"    sgl_viewlist_set_border_color({name}, {sgl_rgb(vl.BorderColor)});");
                sb.AppendLine($"    sgl_viewlist_set_border_width({name}, {vl.BorderWidth});");
                sb.AppendLine($"    sgl_viewlist_set_radius({name}, {vl.Radius});");
                sb.AppendLine($"    sgl_viewlist_set_alpha({name}, {vl.Opacity});");
                sb.AppendLine($"    sgl_viewlist_set_item_height({name}, {vl.ItemHeight});");
                sb.AppendLine($"    sgl_viewlist_set_item_margin({name}, {vl.MarginX}, {vl.MarginY});");

                if (vl.Children != null && vl.Children.Count > 0)
                {
                    sb.AppendLine($"    // Children of {name}");
                    foreach (var child in vl.Children)
                    {
                        sb.Append(GenerateSglCode(child, name));
                        sb.AppendLine($"    sgl_viewlist_append_obj({name}, {child.Id});");
                    }
                }
            }
            else if (d is SglStatusbarData stbar)
            {
                sb.AppendLine($"    sgl_statusbar_set_bg_color({name}, {sgl_rgb(stbar.BgColor)});");
                sb.AppendLine($"    sgl_statusbar_set_bg_alpha({name}, {stbar.BgAlpha});");
                sb.AppendLine($"    sgl_statusbar_set_bg_radius({name}, {stbar.Radius});");
                sb.AppendLine($"    sgl_statusbar_set_slot_space({name}, {stbar.SlotSpace});");
                sb.AppendLine($"    sgl_statusbar_set_slot_margin({name}, {stbar.LeftMargin}, {stbar.RightMargin});");
                if (!string.IsNullOrEmpty(stbar.FontName))
                    sb.AppendLine($"    sgl_statusbar_set_font({name}, &{stbar.FontName});");

                for (int i = 0; i < stbar.LeftSlots.Count; i++)
                {
                    var slot = stbar.LeftSlots[i];
                    sb.AppendLine($"    sgl_statusbar_add_left_slot({name}, {i}, \"{slot.Text}\");");
                    sb.AppendLine($"    sgl_statusbar_set_left_slot_color({name}, {i}, {sgl_rgb(slot.Color)});");
                    sb.AppendLine($"    sgl_statusbar_set_left_slot_alpha({name}, {i}, {slot.Alpha});");
                }
                for (int i = 0; i < stbar.RightSlots.Count; i++)
                {
                    var slot = stbar.RightSlots[i];
                    sb.AppendLine($"    sgl_statusbar_add_right_slot({name}, {i}, \"{slot.Text}\");");
                    sb.AppendLine($"    sgl_statusbar_set_right_slot_color({name}, {i}, {sgl_rgb(slot.Color)});");
                    sb.AppendLine($"    sgl_statusbar_set_right_slot_alpha({name}, {i}, {slot.Alpha});");
                }
            }
            else if (d is SglDropdownData dd)
            {
                sb.AppendLine($"    {name} = sgl_dropdown_create({parentName});");
                sb.AppendLine($"    sgl_obj_set_size({name}, {dd.W}, {dd.H});");
                sb.AppendLine($"    sgl_obj_set_pos({name}, {dd.X}, {dd.Y});");

                // 设置样式
                sb.AppendLine($"    sgl_dropdown_set_bg_color({name}, {sgl_rgb(dd.BgColor)});");
                sb.AppendLine($"    sgl_dropdown_set_text_color({name}, {sgl_rgb(dd.TextColor)});");
                sb.AppendLine($"    sgl_dropdown_set_text_font({name}, &{dd.FontName});");
                sb.AppendLine($"    sgl_dropdown_set_radius({name}, {dd.Radius});");
                sb.AppendLine($"    sgl_dropdown_set_alpha({name}, {dd.Opticaty});");
                sb.AppendLine($"    sgl_dropdown_set_border_width({name}, {dd.BorderWidth});");
                sb.AppendLine($"    sgl_dropdown_set_border_color({name}, {sgl_rgb(dd.BorderColor)});");

                // 导出选项列表
                foreach (var opt in dd.Options)
                {
                    sb.AppendLine($"    sgl_dropdown_add_option({name}, \"{opt}\");");
                }

                // 设置初始选中项
                if (dd.SelectedIndex >= 0)
                {
                    sb.AppendLine($"    //sgl_dropdown_set_selected_index({name}, {dd.SelectedIndex});");
                   
                }
            }
            else if (d is SglRollerData roller)
            {
                // 设置选项文本（使用 dynamic 方式以便 SGL 内部管理内存）
                sb.AppendLine($"    sgl_roller_set_option_dynamic({name}, \"{EscapeCString(roller.Options)}\");");

                // 设置可见行数
                sb.AppendLine($"    sgl_roller_set_visible_rows({name}, {roller.VisibleRows});");

                // 设置样式
                sb.AppendLine($"    sgl_roller_set_bg_color({name}, {sgl_rgb(roller.BgColor)});");
                sb.AppendLine($"    sgl_roller_set_text_color({name}, {sgl_rgb(roller.TextColor)});");
                sb.AppendLine($"    sgl_roller_set_selected_color({name}, {sgl_rgb(roller.SelectedColor)});");
                sb.AppendLine($"    sgl_roller_set_border_color({name}, {sgl_rgb(roller.BorderColor)});");
                sb.AppendLine($"    sgl_roller_set_alpha({name}, {roller.Alpha});");
                sb.AppendLine($"    sgl_roller_set_radius({name}, {roller.Radius});");
                sb.AppendLine($"    sgl_roller_set_border_width({name}, {roller.BorderWidth});");

                // 设置字体
                if (!string.IsNullOrEmpty(roller.FontName))
                {
                    sb.AppendLine($"    sgl_roller_set_text_font({name}, &{roller.FontName});");
                }

                // 设置初始选中项（sgl_roller_set_option_dynamic 默认选第 0 项）
                if (roller.SelectedIndex > 0)
                {
                    sb.AppendLine($"    ((sgl_roller_t*){name})->item_selected = {roller.SelectedIndex};");
                    sb.AppendLine($"    ((sgl_roller_t*){name})->text_offset = sgl_string_option_get_offset(((sgl_roller_t*){name})->opt_text, {roller.SelectedIndex});");
                    sb.AppendLine($"    ((sgl_roller_t*){name})->scroll_y = -{roller.SelectedIndex} * (sgl_font_get_height(((sgl_roller_t*){name})->font) + 6);");
                }
            }
            else if (d is SglCircleData circle)
            {
                // 设置圆形半径 (注意：sgl_circle_set_radius 内部通常会处理对象的 size)
                sb.AppendLine($"    sgl_circle_set_radius({name}, {circle.Radius});");

                // 设置填充颜色和透明度
                sb.AppendLine($"    sgl_circle_set_color({name}, {sgl_rgb(circle.Color)});");
                sb.AppendLine($"    sgl_circle_set_alpha({name}, {circle.Opacity});");

                // 边框属性：只有当宽度大于 0 时才导出，保持代码简洁
                if (circle.BorderWidth > 0)
                {
                    sb.AppendLine($"    sgl_circle_set_border_width({name}, {circle.BorderWidth});");
                    sb.AppendLine($"    sgl_circle_set_border_color({name}, {sgl_rgb(circle.BorderColor)});");
                }

                // 图片填充：如果设置了引用的变量名，则导出设置函数
                if (!string.IsNullOrEmpty(circle.PixmapVarName))
                {
                    // 这里的 & 符号取决于的 PixmapVarName 是结构体名还是指针名，通常 SGL 传入地址
                    sb.AppendLine($"    sgl_circle_set_pixmap({name}, &{circle.Id}_{circle.PixmapVarName}_pixmap);");
                }
            }
            else if (d is SglRingData ring)
            {
                sb.AppendLine($"    sgl_circle_set_alpha({name}, {ring.Opacity});");
                // 设置圆环半径 (内半径, 外半径)
                // SGL 的 sgl_ring_set_radius 内部会处理内径赋值并联动更新外径及对象尺寸
                sb.AppendLine($"    sgl_ring_set_radius({name}, {ring.RadiusIn}, {ring.RadiusOut});");

                // 2. 设置颜色
                sb.AppendLine($"    sgl_ring_set_color({name}, {sgl_rgb(ring.Color)});");


            }
            else if (d is SglKeyboardData kb)
            {
                // 主体属性设置
                sb.AppendLine($"    sgl_keyboard_set_color({name}, {sgl_rgb(kb.BgColor)});");
                sb.AppendLine($"    sgl_keyboard_set_alpha({name}, {kb.Opacity});");
                sb.AppendLine($"    sgl_keyboard_set_radius({name}, {kb.Radius});");
                sb.AppendLine($"    sgl_keyboard_set_border_color({name}, {sgl_rgb(kb.BorderColor)});");
                sb.AppendLine($"    sgl_keyboard_set_border_width({name}, {kb.BorderWidth});");

                // 2. 按键属性设置
                sb.AppendLine($"    sgl_keyboard_set_btn_color({name}, {sgl_rgb(kb.BtnColor)});");
                sb.AppendLine($"    sgl_keyboard_set_btn_alpha({name}, {kb.BtnAlpha});");
                sb.AppendLine($"    sgl_keyboard_set_btn_radius({name}, {kb.BtnRadius});");
                sb.AppendLine($"    sgl_keyboard_set_btn_border_color({name}, {sgl_rgb(kb.BtnBorderColor)});");
                sb.AppendLine($"    sgl_keyboard_set_btn_border_width({name}, {kb.BtnBorderWidth});");

                //  文本、字体与布局
                sb.AppendLine($"    sgl_keyboard_set_text_color({name}, {sgl_rgb(kb.TextColor)});");
                if (!string.IsNullOrEmpty(kb.FontName))
                {
                    sb.AppendLine($"    sgl_keyboard_set_text_font({name}, &{kb.FontName});");
                }

                // 只有非 0 时导出 margin，否则 sgl 内部会计算默认值
                if (kb.KeyMargin > 0)
                {
                    sb.AppendLine($"    ((sgl_keyboard_t*){name})->key_margin = {kb.KeyMargin};");
                }
            }
            else if (d is SglNumberKbdData numkb)
            {


                // 2. 主体外壳 (Body) 属性
                sb.AppendLine($"    sgl_numberkbd_set_color({name}, {sgl_rgb(numkb.BgColor)});");
                sb.AppendLine($"    sgl_numberkbd_set_alpha({name}, {numkb.Opacity});");
                sb.AppendLine($"    sgl_numberkbd_set_radius({name}, {numkb.Radius});"); // 同时设置主体和按键基础圆角

                // 颜色设置 
                sb.AppendLine($"    sgl_numberkbd_set_border_color({name}, {sgl_rgb(numkb.BorderColor)});");
                sb.AppendLine($"    sgl_numberkbd_set_border_width({name}, {numkb.BorderWidth});");

                //  按键 (Button) 属性
                sb.AppendLine($"    sgl_numberkbd_set_btn_color({name},  {sgl_rgb(numkb.BtnColor)} );");
                sb.AppendLine($"    sgl_numberkbd_set_btn_border_color({name}, {sgl_rgb(numkb.BtnBorderColor)});");
                sb.AppendLine($"    sgl_numberkbd_set_btn_border_width({name}, {numkb.BtnBorderWidth});");
                sb.AppendLine($"    sgl_numberkbd_set_btn_margin({name}, {numkb.BtnMargin});");

                // 如果需要单独设置按键圆角（源码中 set_radius 会覆盖 btn_radius，所以后设置）
                sb.AppendLine($"    sgl_numberkbd_set_btn_radius({name}, {numkb.BtnRadius});");

                //  文本属性
                sb.AppendLine($"    sgl_numberkbd_set_text_color({name}, {sgl_rgb(numkb.TextColor)});");

                // 字体设置：需要根据的字体管理系统导出对应的字体指针变量名
                if (!string.IsNullOrEmpty(numkb.FontName))
                {
                    sb.AppendLine($"    sgl_numberkbd_set_text_font({name}, &{numkb.FontName});");
                }
            }
            else if (d is SglLineData line)
            {
                // 获取容器的绝对位置和尺寸
                int x = line.X;
                int y = line.Y;
                int w = line.W;
                int h = line.H;

                // 2. 初始化绝对坐标点
                int x1_abs, y1_abs, x2_abs, y2_abs;

                //  计算：容器基准坐标 + 方向带来的偏移量
                switch (line.Direction)
                {
                    case LineDirection.Horizontal:
                        x1_abs = x; x2_abs = x + w;
                        y1_abs = y + h / 2; y2_abs = y + h / 2;
                        break;

                    case LineDirection.Vertical:
                        x1_abs = x + w / 2; x2_abs = x + w / 2;
                        y1_abs = y; y2_abs = y + h;
                        break;

                    case LineDirection.Diagonal: // \
                        x1_abs = x; y1_abs = y;
                        x2_abs = x + w; y2_abs = y + h;
                        break;

                    case LineDirection.ReverseDiagonal: // /
                        x1_abs = x; y1_abs = y + h;
                        x2_abs = x + w; y2_abs = y;
                        break;

                    default: // 默认水平
                        x1_abs = x; x2_abs = x + w;
                        y1_abs = y + h / 2; y2_abs = y + h / 2;
                        break;
                }

                //  写入生成的 C 代码
                sb.AppendLine($"    // --- 绝对坐标线条: {name} ---");

                // 注意：在绝对坐标模式下，sgl_line_set_pos 传入的是屏幕物理像素点
                sb.AppendLine($"    sgl_line_set_pos({name}, {x1_abs}, {y1_abs}, {x2_abs}, {y2_abs});");

                // 样式设置
                sb.AppendLine($"    sgl_line_set_color({name}, {sgl_rgb(line.Color)});");
                sb.AppendLine($"    sgl_line_set_alpha({name}, {line.Opacity});");
                sb.AppendLine($"    sgl_line_set_width({name}, {line.LineWidth});");
            }
            else if (d is SglBarchartData chart)
            {

                // 绑定 X 轴标签数组 
                // 注意：在生成的 C 代码中，labels 需要是 static 或全局变量
                sb.AppendLine($"    sgl_barchart_set_x_labels({name}, {chart.Id}_labels, {chart.XLabelCount});");

                // 2. 开启 X 轴标签显示
                sb.AppendLine($"    sgl_barchart_enable_axis_labels({name}, SGL_BARCHART_AXIS_X, {(chart.ShowXLabels ? "true" : "false")});");

                //  开启 X 轴刻度线 (可选)
                sb.AppendLine($"    sgl_barchart_enable_axis_ticks({name}, SGL_BARCHART_AXIS_X, {(chart.ShowXTicks ? "true" : "false")});");

                //  设置 X 轴步长 (分类轴通常设为 1)
                sb.AppendLine($"    sgl_barchart_set_axis_step({name}, SGL_BARCHART_AXIS_X, {chart.XStep});");

                //  设置 X 轴字体与颜色
                sb.AppendLine($"    sgl_barchart_set_axis_label_font({name}, SGL_BARCHART_AXIS_X, &{chart.XFontName});");
                sb.AppendLine($"    sgl_barchart_set_axis_label_color({name}, SGL_BARCHART_AXIS_X, {sgl_rgb(chart.XLabelColor)}, {chart.Opacity});");

                //  确保 X 轴范围正确（如果 labels 数量变了，auto_scale 很有用）
                if (chart.XAutoScale)
                    sb.AppendLine($"    sgl_barchart_enable_axis_auto_scale({name}, SGL_BARCHART_AXIS_X, true);");

                // 2. Y轴核心配置与范围
                if (chart.YAutoScale)
                    sb.AppendLine($"    sgl_barchart_enable_axis_auto_scale({name}, SGL_BARCHART_AXIS_Y, true);");
                else
                    sb.AppendLine($"    sgl_barchart_set_axis_range({name}, SGL_BARCHART_AXIS_Y, {chart.YMin}, {chart.YMax});");

                //  网格配置 (使用细化的 YGridColor 和 YGridDashed)
                sb.AppendLine($"    sgl_barchart_enable_axis_grid({name}, SGL_BARCHART_AXIS_Y, {(chart.ShowYGrid ? "true" : "false")});");
                sb.AppendLine($"    sgl_barchart_set_axis_grid_style({name}, SGL_BARCHART_AXIS_Y, {(chart.YGridDashed ? "1" : "0")});");
                sb.AppendLine($"    sgl_barchart_set_axis_grid_color({name}, SGL_BARCHART_AXIS_Y, {sgl_rgb(chart.YGridColor)},{chart.Opacity});");

                //  间距、方向与序列
                sb.AppendLine($"    sgl_barchart_set_bar_spacing({name}, {chart.BarGap}, {chart.CategoryGap});");
                sb.AppendLine($"    sgl_barchart_set_orientation({name}, {(chart.Orientation == SglBarchartOrientation.Horizontal ? "SGL_BARCHART_ORIENTATION_HORIZONTAL" : "SGL_BARCHART_ORIENTATION_VERTICAL")});");
                sb.AppendLine($"    sgl_barchart_set_series_count({name}, {chart.SeriesCount});");
                sb.AppendLine($"    sgl_barchart_set_series_y_array({name}, 0,{chart.Id}_values, sizeof({chart.Id}_values)/sizeof({chart.Id}_values[0]));");
                sb.AppendLine($"    sgl_barchart_set_series_color({name},0,{sgl_rgb(chart.BarColor1)}, {chart.Opacity});");

                //  标签、刻度线与步进
                sb.AppendLine($"    sgl_barchart_enable_axis_labels({name}, SGL_BARCHART_AXIS_Y, {(chart.ShowYLabels ? "true" : "false")});");
                sb.AppendLine($"    sgl_barchart_enable_axis_ticks({name}, SGL_BARCHART_AXIS_Y, {(chart.ShowYTicks ? "true" : "false")});");

                // 如果 YStep 为 0，SGL 会自动根据 AutoDivisions 计算，所以这里直接导出即可
                sb.AppendLine($"    sgl_barchart_set_axis_step({name}, SGL_BARCHART_AXIS_Y, {chart.YStep});");
                if (chart.YStep <= 0)
                    sb.AppendLine($"    sgl_barchart_set_axis_auto_divisions({name}, SGL_BARCHART_AXIS_Y, {chart.YAutoDivisions});");

                sb.AppendLine($"    sgl_barchart_set_axis_label_color({name}, SGL_BARCHART_AXIS_Y, {sgl_rgb(chart.YLabelColor)}, {chart.Opacity});");
                sb.AppendLine($"    sgl_barchart_set_axis_label_font({name}, SGL_BARCHART_AXIS_Y, &{chart.YFontName});");

                //  绘图区控制 (如果开启了自定义绘图区)
                if (chart.CustomPlotRect)
                {
                    sb.AppendLine($"    sgl_barchart_set_plot_area_rel({name}, {(short)chart.PlotRelRect.X}, {(short)chart.PlotRelRect.Y}, {(short)chart.PlotRelRect.Width}, {(short)chart.PlotRelRect.Height});");
                }

                //  动画配置
                if (chart.EnableOpenAnim)
                {
                    sb.AppendLine($"    sgl_barchart_enable_open_anim({name}, true);");
                    sb.AppendLine($"    sgl_barchart_set_open_anim_dir({name}, (sgl_barchart_open_anim_dir_t){(int)chart.OpenAnimDir});");
                    sb.AppendLine($"    sgl_barchart_set_open_anim_duration({name}, {chart.OpenAnimDuration});");
                }

                //  基础外观与颜色
                sb.AppendLine($"    sgl_barchart_set_bg_color({name}, {sgl_rgb(chart.BgColor)});");
                sb.AppendLine($"    sgl_barchart_set_bg_alpha({name}, {chart.BgAlpha});");
                sb.AppendLine($"    sgl_barchart_set_border_color({name}, {sgl_rgb(chart.BorderColor)} );");
                sb.AppendLine($"    sgl_barchart_set_alpha({name}, {chart.Opacity});");
                sb.AppendLine($"    sgl_barchart_set_layout_padding({name}, {chart.LayoutLeftMargin}, {chart.LayoutTopMargin}, {chart.LayoutRightMargin}, {chart.LayoutBottomMargin});");

                //  更新/刷新
                sb.AppendLine($"    sgl_barchart_update({name});");
            }
            else if (d is SglPiechartData pie)
            {


                // 基础样式与透明度
                sb.AppendLine($"    sgl_piechart_set_alpha({name}, {pie.Opacity});");
                sb.AppendLine($"    sgl_piechart_set_start_angle({name}, {pie.StartAngle});");
                sb.AppendLine($"    sgl_piechart_set_radius({name}, {pie.RadiusOut});");
                sb.AppendLine($"    sgl_piechart_set_inner_radius_rate({name}, {pie.InnerRadiusRate});");
                sb.AppendLine($"    sgl_piechart_set_smooth({name}, {(pie.IsSmooth ? "true" : "false")});");

                // 2. 切片数据配置
                // SGL 内部会重新分配内存，因此必须先设置 Count
                sb.AppendLine($"    sgl_piechart_set_slice_count({name}, {pie.Slices.Count});");
                for (int i = 0; i < pie.Slices.Count; i++)
                {
                    var slice = pie.Slices[i];
                    // 建议使用 Convenient function 减少代码行数
                    // 注意：label 必须是持久化字符串指针
                    sb.AppendLine($"    sgl_piechart_set_slice({name}, {i}, {slice.Value}, {sgl_rgb(slice.Color)}, \"{slice.Label}\");");
                    if (slice.Opacity < 255)
                    {
                        sb.AppendLine($"    sgl_piechart_set_slice_alpha({name}, {i}, {slice.Opacity});");
                    }
                }

                //  图例 (Legend) 设置
                sb.AppendLine($"    sgl_piechart_enable_legend({name}, {(pie.LegendEnable ? "true" : "false")});");
                if (pie.LegendEnable)
                {
                    // 转换位置枚举 (SglPieLegendPos -> sgl_piechart_legend_pos_t)
                    string posStr = pie.LegendPos switch
                    {
                        SglPieLegendPos.Left => "SGL_PIECHART_LEGEND_POS_LEFT",
                        SglPieLegendPos.Right => "SGL_PIECHART_LEGEND_POS_RIGHT",
                        SglPieLegendPos.Top => "SGL_PIECHART_LEGEND_POS_TOP",
                        SglPieLegendPos.Bottom => "SGL_PIECHART_LEGEND_POS_BOTTOM",
                        _ => "SGL_PIECHART_LEGEND_POS_NONE"
                    };
                    sb.AppendLine($"    sgl_piechart_set_legend_pos({name}, {posStr});");

                    string dirStr = pie.LegendDir == SglPieLegendDir.Horizontal ?
                                    "SGL_PIECHART_LEGEND_DIR_HORIZONTAL" : "SGL_PIECHART_LEGEND_DIR_VERTICAL";
                    sb.AppendLine($"    sgl_piechart_set_legend_dir({name}, {dirStr});");

                    sb.AppendLine($"    sgl_piechart_set_legend_area_size({name}, {pie.LegendAreaSize});");
                    sb.AppendLine($"    sgl_piechart_set_legend_box_size({name}, {pie.LegendBoxSize});");
                    sb.AppendLine($"    sgl_piechart_set_legend_text_color({name}, {sgl_rgb(pie.LegendTextColor)});");

                    // 字体 (引用全局字体变量)

                    sb.AppendLine($"    sgl_piechart_set_legend_font({name}, &{pie.FontName});");
                }

                //  图例背景配置
                sb.AppendLine($"    sgl_piechart_enable_legend_bg({name}, {(pie.LegendBgEnable ? "true" : "false")});");
                if (pie.LegendBgEnable)
                {
                    sb.AppendLine($"    sgl_piechart_set_legend_bg_color({name}, {sgl_rgb(pie.LegendBgColor)});");
                }

                //  动画配置
                sb.AppendLine($"    sgl_piechart_enable_open_anim({name}, {(pie.OpenAnimEnable ? "true" : "false")});");

                //  强制重绘
                sb.AppendLine($"    sgl_obj_set_dirty({name});");
            }
            else if (d is SglLinechartData lc)
            {
                // 创建与基础设置
                sb.AppendLine($"    sgl_linechart_set_series_count({name}, 1);");
                sb.AppendLine($"    sgl_obj_set_border_width({name}, {lc.BorderWidth});");
                sb.AppendLine($"    sgl_obj_set_radius({name}, {lc.Radius});");
                sb.AppendLine($"    sgl_linechart_set_bg_color({name}, {sgl_rgb(lc.BgColor)});");
                sb.AppendLine($"    sgl_linechart_set_bg_alpha({name}, {lc.BgAlpha});");
                sb.AppendLine($"    sgl_linechart_set_border_color({name}, {sgl_rgb(lc.BorderColor)});");
                sb.AppendLine($"    sgl_linechart_set_alpha({name}, {lc.Opacity});");

                // 2. 坐标轴范围
                if (lc.YAutoScale)
                    sb.AppendLine($"    sgl_linechart_enable_axis_auto_scale({name}, SGL_LINECHART_AXIS_Y, true);");
                else
                    sb.AppendLine($"    sgl_linechart_set_axis_range({name}, SGL_LINECHART_AXIS_Y, {lc.YMin}, {lc.YMax});");

                int lineValueCount = (lc.Values != null && lc.Values.Count > 0) ? lc.Values.Count : 1;
                int xMax = Math.Max(0, lineValueCount - 1);
                sb.AppendLine($"    sgl_linechart_set_axis_range({name}, SGL_LINECHART_AXIS_X, 0, {xMax});");
                sb.AppendLine($"    sgl_linechart_set_axis_step({name}, SGL_LINECHART_AXIS_X, 1);");

                //  绘图区布局 (SGL 使用相对矩形控制)
                sb.AppendLine($"    sgl_linechart_set_plot_area_rel({name}, {lc.PlotOffsetX}, {lc.PlotOffsetY}, {lc.PlotWidth}, {lc.PlotHeight});");

                //  序列样式配置 (Series Index 0)
                // 自动判断显示模式
                string mode = (lc.PointType != SglLinePointType.None) ? "SGL_LINECHART_SERIES_MODE_LINE_AND_POINT" : "SGL_LINECHART_SERIES_MODE_LINE";
                sb.AppendLine($"    sgl_linechart_set_series_mode({name}, 0, {mode});");
                sb.AppendLine($"    sgl_linechart_set_series_line_width({name}, 0, {lc.LineThickness});");
                sb.AppendLine($"    sgl_linechart_set_series_line_color({name}, 0, {sgl_rgb(lc.LineColor)});");
                sb.AppendLine($"    sgl_linechart_set_series_line_alpha({name}, 0, {lc.LineOpacity});");

                // 填充设置
                if (lc.FillUnder)
                {
                    sb.AppendLine($"    sgl_linechart_enable_series_fill({name}, 0, true);");
                    sb.AppendLine($"    sgl_linechart_set_series_fill_color({name}, 0, {sgl_rgb(lc.FillColor)}, {lc.FillOpacity});");
                }

                // 点样式
                if (lc.PointType != SglLinePointType.None)
                {
                    string shape = lc.PointType == SglLinePointType.Circle ? "SGL_LINECHART_POINT_SHAPE_CIRCLE" : "SGL_LINECHART_POINT_SHAPE_SQUARE";
                    sb.AppendLine($"    sgl_linechart_set_series_point_style({name}, 0, {shape}, {lc.PointRadius});");
                }

                //  辅助设施
                sb.AppendLine($"    sgl_linechart_enable_axis_grid({name}, SGL_LINECHART_AXIS_Y, {(lc.ShowYGrid ? "true" : "false")});");
                sb.AppendLine($"    sgl_linechart_enable_axis_labels({name}, SGL_LINECHART_AXIS_Y, {(lc.ShowYLabels ? "true" : "false")});");
                if (!string.IsNullOrEmpty(lc.YFontName))
                {
                    sb.AppendLine($"    sgl_linechart_set_axis_label_font({name}, SGL_LINECHART_AXIS_Y, &{lc.YFontName});");
                }

                sb.AppendLine($"    sgl_linechart_set_axis_step({name}, SGL_LINECHART_AXIS_Y, {lc.YStep});");
                sb.AppendLine($"    sgl_linechart_set_axis_auto_divisions({name}, SGL_LINECHART_AXIS_Y, {lc.YDivisions});");
                sb.AppendLine($"    sgl_linechart_set_axis_grid_color({name}, SGL_LINECHART_AXIS_Y, {sgl_rgb(lc.YGridColor)}, {lc.YGridAlpha});");
                sb.AppendLine($"    sgl_linechart_set_axis_label_color({name}, SGL_LINECHART_AXIS_Y, {sgl_rgb(lc.YLabelColor)}, {lc.YLabelAlpha});");
                sb.AppendLine($"    sgl_linechart_enable_axis_ticks({name}, SGL_LINECHART_AXIS_Y, {(lc.ShowYTicks ? "true" : "false")});");
                sb.AppendLine($"    sgl_linechart_set_axis_grid_style({name}, SGL_LINECHART_AXIS_Y, {(lc.YGridDashed ? "1" : "0")});");

                sb.AppendLine($"    sgl_linechart_enable_axis_grid({name}, SGL_LINECHART_AXIS_X, {(lc.ShowXGrid ? "true" : "false")});");
                sb.AppendLine($"    sgl_linechart_enable_axis_labels({name}, SGL_LINECHART_AXIS_X, {(lc.ShowXLabels ? "true" : "false")});");
                sb.AppendLine($"    sgl_linechart_enable_axis_ticks({name}, SGL_LINECHART_AXIS_X, {(lc.ShowXTicks ? "true" : "false")});");
                sb.AppendLine($"    sgl_linechart_set_axis_grid_style({name}, SGL_LINECHART_AXIS_X, {(lc.XGridDashed ? "1" : "0")});");
                sb.AppendLine($"    sgl_linechart_set_axis_grid_color({name}, SGL_LINECHART_AXIS_X, {sgl_rgb(lc.XGridColor)}, {lc.XGridAlpha});");
                sb.AppendLine($"    sgl_linechart_set_axis_label_color({name}, SGL_LINECHART_AXIS_X, {sgl_rgb(lc.XLabelColor)}, {lc.XLabelAlpha});");
                if (!string.IsNullOrEmpty(lc.XFontName))
                {
                    sb.AppendLine($"    sgl_linechart_set_axis_label_font({name}, SGL_LINECHART_AXIS_X, &{lc.XFontName});");
                }
                sb.AppendLine($"    sgl_linechart_set_x_labels({name}, {name}_labels, {lineValueCount});");

                //  数据绑定 (假设生成的 C 文件中存在对应的静态数据数组)
                sb.AppendLine($"    sgl_linechart_set_series_y_array({name}, 0, {name}_pts, {lineValueCount});");

                //  动画与刷新
                if (lc.EnableOpenAnim)
                {
                    sb.AppendLine($"    sgl_linechart_enable_open_anim({name}, true);");
                    string animDir = lc.OpenAnimDir == SglLineOpenAnimDir.FromTop ? "SGL_LINECHART_OPEN_ANIM_FROM_TOP" : "SGL_LINECHART_OPEN_ANIM_FROM_LEFT";
                    sb.AppendLine($"    sgl_linechart_set_open_anim_dir({name}, {animDir});");
                }

                sb.AppendLine($"    sgl_linechart_update({name});");
            }
            else if (d is SglIconData icon)
            {


                // 资源名加 & 符号以匹配 C 语言地址传参
                sb.AppendLine($"    sgl_icon_set_icon({name}, &{icon.Id}_{icon.IconName}_pixmap);");

                // 颜色转换，使用的 sgl_rgb 辅助函数
                sb.AppendLine($"    sgl_icon_set_color({name}, {sgl_rgb(icon.IconColor)} );");

                if (icon.Opacity < 255)
                {
                    sb.AppendLine($"    sgl_icon_set_alpha({name}, {icon.Opacity});");
                }

                if (icon.IconAlign != 0)
                {
                    sb.AppendLine($"    sgl_icon_set_align({name}, {icon.IconAlign});");
                }
            }
            else if (d is SglExtImageData extImg)
            {


                // 2. 设置图像资源 (pixmap)
                if (!string.IsNullOrEmpty(extImg.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_img_ext_set_pixmap({name}, &{extImg.Id}_{extImg.PixmapVarName}_pixmap);");
                }

                //  设置读取函数 (read ops)
                //if (!string.IsNullOrEmpty(extImg.ReadFuncName))
                //{
                //    sb.AppendLine($"    sgl_img_ext_set_read_ops({name}, {extImg.ReadFuncName});");
                //}

                //  设置透明度
                if (extImg.Opacity < 255)
                {
                    sb.AppendLine($"    sgl_img_ext_set_alpha({name}, {extImg.Opacity});");
                }

                ////  设置多帧/动画属性
                //if (extImg.PixmapNum > 1)
                //{
                //    string autoStr = extImg.AutoRefresh ? "true" : "false";
                //    sb.AppendLine($"    sgl_img_ext_set_pixmap_num({name}, {extImg.PixmapNum}, {autoStr});");
                //}
            }
            else if (d is SglQrcodeData qr)
            {
                sb.AppendLine($"    sgl_obj_set_size({name}, {qr.W}, {qr.H});");
                sb.AppendLine($"    sgl_qrcode_set_text({name}, \"{EscapeCString(qr.Url)}\");");
                sb.AppendLine($"    sgl_qrcode_set_version({name}, {qr.QrVersion});");
                sb.AppendLine($"    sgl_qrcode_set_ecc({name}, {qr.QrEcc});");
                sb.AppendLine($"    sgl_qrcode_set_scale({name}, {qr.QrScale});");
                sb.AppendLine($"    sgl_qrcode_set_zone({name}, {qr.QrQuietZone});");
                sb.AppendLine($"    sgl_qrcode_set_alpha({name}, {qr.Opacity});");
                sb.AppendLine($"    sgl_qrcode_set_bg_color({name}, {sgl_rgb(qr.BgColor)});");
                sb.AppendLine($"    sgl_qrcode_set_cell_color({name}, {sgl_rgb(qr.CellColor)});");
                if (qr.CellRadius > 0)
                {
                    sb.AppendLine($"    sgl_qrcode_set_cell_radius({name}, {qr.CellRadius});");
                }
                if (qr.LogoRadius > 0)
                {
                    sb.AppendLine($"    sgl_qrcode_set_logo_radius({name}, {qr.LogoRadius});");
                }
                if (!string.IsNullOrEmpty(qr.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_qrcode_set_logo({name}, &{qr.Id}_{qr.PixmapVarName}_pixmap);");
                }
            }
            else if (d is SglBoxData box)
            {

                sb.AppendLine($"    sgl_box_set_bg_color({name}, {sgl_rgb(box.BgColor)});");
                sb.AppendLine($"    sgl_box_set_alpha({name}, {box.Opacity});");
                sb.AppendLine($"    sgl_box_set_radius({name}, {box.Radius});");
                sb.AppendLine($"    sgl_box_set_border_width({name}, {box.BorderWidth});");
                sb.AppendLine($"    sgl_box_set_border_color({name}, {sgl_rgb(box.BorderColor)});");
                //sb.AppendLine($"    sgl_box_set_scroll_mode({name}, {(int)box.ScrollMode});");
                sb.AppendLine($"    sgl_box_set_scrollbar_color({name}, {sgl_rgb(box.ScrollbarColor)});");
                sb.AppendLine($"    sgl_box_set_show_scrollbar({name}, {(box.ShowVerticalScrollbar ? 1 : 0)}, {(box.ShowHorizontalScrollbar ? 1 : 0)});");
                sb.AppendLine($"    sgl_box_set_elastic_scroll({name}, {box.ElasticScrollUp}, {box.ElasticScrollDown}, {box.ElasticScrollLeft}, {box.ElasticScrollRight});");

                if (!string.IsNullOrEmpty(box.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_box_set_pixmap({name}, &{box.Id}_{box.PixmapVarName}_pixmap);");
                }
                if (d.IsClickable == true && !string.IsNullOrEmpty(d.EventCallbackName))
                {
                    sb.AppendLine($"    sgl_obj_set_clickable({name});");
                    sb.AppendLine($"    sgl_obj_set_event_cb({name}, {d.EventCallbackName},NULL);");

                }

                if (box.Children != null && box.Children.Count > 0)
                {
                    sb.AppendLine($"    // Children of {name}");
                    foreach (var child in box.Children)
                    {
                        sb.Append(GenerateSglCode(child, name));
                    }
                }
                return sb.ToString();
            }
            else if (d is SglPanelData panel)
            {

                sb.AppendLine($"    sgl_rect_set_color({name}, {sgl_rgb(panel.BgColor)});");
                sb.AppendLine($"    sgl_rect_set_alpha({name}, {panel.Opacity});");
                sb.AppendLine($"    sgl_rect_set_radius({name}, {panel.Radius});");
                sb.AppendLine($"    sgl_rect_set_border_width({name}, {panel.BorderWidth});");
                sb.AppendLine($"    sgl_rect_set_border_color({name}, {sgl_rgb(panel.BorderColor)});");
                sb.AppendLine($"    sgl_rect_set_border_alpha({name}, {panel.BorderOpacity});");
                // 2. 设置图像资源 (pixmap)
                if (!string.IsNullOrEmpty(panel.PixmapVarName))
                {
                    sb.AppendLine($"    sgl_rect_set_pixmap({name}, &{panel.Id}_{panel.PixmapVarName}_pixmap);");
                }
                // 2. 绑定事件回调 (核心添加)
                if (d.IsClickable == true && !string.IsNullOrEmpty(d.EventCallbackName))
                {
                    // 如果的基类有 IsClickable 属性，记得同步
                    sb.AppendLine($"    sgl_obj_set_clickable({name});");
                    sb.AppendLine($"    sgl_obj_set_event_cb({name}, {d.EventCallbackName},NULL);");

                }

                // --- 处理子对象 ---
                if (panel.Children != null && panel.Children.Count > 0)
                {
                    sb.AppendLine($"    // Children of {name}");
                    foreach (var child in panel.Children)
                    {
                        // 递归生成子对象代码，将当前 panel 的名称作为 parent 传入
                        sb.Append(GenerateSglCode(child, name));
                    }
                }
                return sb.ToString();
            }

            // 2. 绑定事件回调 (核心添加)
            if (d.IsClickable == true && !string.IsNullOrEmpty(d.EventCallbackName))
            {
                // 如果的基类有 IsClickable 属性，记得同步
                sb.AppendLine($"    sgl_obj_set_clickable({name});");
                sb.AppendLine($"    sgl_obj_set_event_cb({name}, {d.EventCallbackName},NULL);");

            }



            return sb.ToString();
        }



        // 生成事件处理函数的 C 语言模板
        public static string GenerateCEventHandlers(SglWidgetData d, HashSet<string> processed)
        {
            // 如果该控件没有任何定义的事件，直接处理子控件并返回
            if (d.Events == null || d.Events.Count == 0)
            {
                StringBuilder childSb = new StringBuilder();
                foreach (var child in d.Children)
                    childSb.Append(GenerateCEventHandlers(child, processed));
                return childSb.ToString();
            }

            StringBuilder sb = new StringBuilder();
            // 生成外部函数头文件
            foreach (var eventItem in d.Events)
            {
                if (eventItem?.Actions == null) continue;

                foreach (var action in eventItem.Actions)
                {
                    if (action == null) continue;

                    // 根据动作的真实类型进行匹配
                    // 如果 action 的实例是 SglCallFunctionAction，则将其重命名为 callAct
                    if (action is SglCallFunctionAction callAct)
                    {
                        // 访问子类特有的属性（假设子类里定义的属性叫 FunctionName）
                        if (!string.IsNullOrEmpty(callAct.FuncName))
                        {
                            // 检查是否已经添加过，避免重复 extern（可选）
                            string funcLine = $"extern void {callAct.FuncName}(sgl_event_t* e);";
                            if (!sb.ToString().Contains(funcLine))
                            {
                                sb.AppendLine(funcLine);
                            }
                        }
                    }
                    // 如果以后有其他需要生成头文件的动作类型，可以在这里继续 else if
                }
            }
            // 生成具体的事件处理函数（Stub）
            foreach (var eventItem in d.Events)
            {
                if (eventItem == null) continue;

                // 生成事件处理函数名
                string handlerName = $"{d.Id}_{eventItem.Trigger.ToString().ToLower()}";

                // 避免重复生成同一个函数
                if (!processed.Contains(handlerName))
                {
                    sb.AppendLine($"// {d.Id} 控件的 {eventItem.Trigger} 事件处理");
                    sb.AppendLine($"sgl_weak_fn void {handlerName}(sgl_event_t *e)");
                    sb.AppendLine("{");
                    sb.AppendLine($"\n   SGL_LOG_INFO(\"{d.Id} {eventItem.Trigger.ToString().ToLower()}\");");


                    // 生成动作代码
                    if (eventItem.Actions != null && eventItem.Actions.Count > 0)
                    {
                        int actionIndex = 1;
                        foreach (var action in eventItem.Actions)
                        {
                            if (action == null) continue;

                            sb.AppendLine($"    // Action {actionIndex}: {action.ActionType}");

                            // 使用 C# 的模式匹配直接转换类型并访问属性
                            switch (action)
                            {
                                // 调用函数
                                case SglCallFunctionAction callAct:
                                    if (!string.IsNullOrEmpty(callAct.FuncName))
                                        sb.AppendLine($"    {callAct.FuncName}(e);");
                                    else
                                        sb.AppendLine($"    // 请指定函数名");
                                    break;

                                // 2. 切换屏幕
                                case SglChangeScreenAction changeAct:
                                    if (!string.IsNullOrEmpty(changeAct.TargetPage))
                                    {
                                        // 防御性检查：验证目标屏幕仍然存在
                                        bool pageExists = SglScreen.Instance.ScreenList
                                            .Any(s => s.Id.Equals(changeAct.TargetPage, StringComparison.OrdinalIgnoreCase));
                                        if (pageExists)
                                            sb.AppendLine($"    ui_screen_load(UI_{changeAct.TargetPage.ToUpper()});");
                                        else
                                            sb.AppendLine($"    // 警告: 目标屏幕 \"{changeAct.TargetPage}\" 已被删除");
                                    }
                                    else
                                        sb.AppendLine($"    // 请指定目标屏幕ID");
                                    break;

                                //  修改属性
                                case SglSetPropertyAction setPropAct:
                                    if (setPropAct.Target != null && !string.IsNullOrEmpty(setPropAct.Value))
                                        sb.AppendLine($"    ui_obj_set_property({setPropAct.Target}, {setPropAct.PropertyType.ToString().ToUpper()}, {setPropAct.Value});");
                                    else
                                        sb.AppendLine($"    // 请指定目标ID、属性名和值");
                                    break;

                                //  修改标志 (Flag)
                                case SglModifyFlagAction flagAct:
                                    // 假设子类有 TargetId 和具体的 Flag 属性
                                    if (flagAct.Target != null)
                                        sb.AppendLine($"    ui_obj_set_flag({flagAct.Target}, {flagAct.FlagType.ToString().ToUpper()});");
                                    else
                                        sb.AppendLine($"    // 请指定目标ID");
                                    break;

                                default:
                                    sb.AppendLine($"    // 未实现的动作类型: {action.ActionType}");
                                    break;
                            }
                            actionIndex++;
                        }
                    }
                    else
                    {
                        sb.AppendLine("    // 没有定义动作");
                    }

                    sb.AppendLine("}\n");
                    processed.Add(handlerName);
                }
            }

            // 2. 生成总入口分发函数（如果控件有事件回调名）
            if (!string.IsNullOrEmpty(d.EventCallbackName))
            {
                sb.AppendLine($"// {d.Id} 的事件分发路由函数");
                sb.AppendLine($"void {d.EventCallbackName}(sgl_event_t *event) {{");
                sb.AppendLine("    switch(event->type) {");

                foreach (var eventItem in d.Events)
                {
                    if (eventItem == null) continue;

                    // 将枚举转为 SGL 宏格式
                    string eventEnumName = eventItem.Trigger.ToString().ToSnakeCase().ToUpper();
                    string macroName = $"SGL_EVENT_{eventEnumName}";

                    string handlerName = $"{d.Id}_{eventItem.Trigger.ToString().ToLower()}";

                    sb.AppendLine($"        case {macroName}:");
                    sb.AppendLine($"            {handlerName}(event);");
                    sb.AppendLine($"            break;");
                }

                sb.AppendLine("        default: break;");
                sb.AppendLine("    }");
                sb.AppendLine("}\n");
            }

            //  生成事件绑定代码
            //sb.AppendLine($"// 绑定 {d.Id} 的事件处理器");
            //sb.AppendLine($"void bind_{d.Id}_events(sgl_obj_t* obj) {{");

            //// 如果控件有事件回调名，则绑定总入口函数
            //if (!string.IsNullOrEmpty(d.EventCallbackName))
            //{
            //    sb.AppendLine($"    sgl_obj_set_event_cb(obj, {d.EventCallbackName});");
            //}

            //// 绑定具体事件
            //foreach (var eventItem in d.Events)
            //{
            //    if (eventItem == null) continue;

            //    string eventEnumName = eventItem.Trigger.ToString().ToSnakeCase().ToUpper();
            //    string macroName = $"SGL_EVENT_{eventEnumName}";

            //    sb.AppendLine($"    sgl_obj_add_event_cb(obj, {macroName}, {d.Id}_{eventItem.Trigger.ToString().ToLower()});");
            //}

            //sb.AppendLine("}\n");

            //  递归子控件
            foreach (var child in d.Children)
            {
                sb.Append(GenerateCEventHandlers(child, processed));
            }

            return sb.ToString();
        }

        // 生成完整的 C 代码文件
        public static string GenerateCEventCode(SglWidgetData rootWidget)
        {
            StringBuilder sb = new StringBuilder();

            // 文件头
            sb.AppendLine("// 自动生成的事件处理代码");
            sb.AppendLine("// 生成时间: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("// 基于 SGL 事件系统");
            sb.AppendLine();
            sb.AppendLine("#include \"sgl.h\"");
            sb.AppendLine("#include <stdio.h>");
            sb.AppendLine();

            // 生成所有事件处理函数
            HashSet<string> processed = new HashSet<string>();
            sb.Append(GenerateCEventHandlers(rootWidget, processed));

            // 生成初始化函数
            sb.AppendLine("// 初始化所有事件处理器");
            sb.AppendLine("void init_all_event_handlers() {");
            sb.AppendLine("    // 在这里初始化所有控件的事件绑定");
            sb.AppendLine("    // 例如: bind_button1_events(sgl_obj_get_by_id(NULL, \"button1\"));");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // 辅助方法：将PascalCase转换为snake_case
        public static string ToSnakeCase(this string str)
        {
            if (string.IsNullOrEmpty(str)) return str;

            var result = new StringBuilder();
            result.Append(char.ToLower(str[0]));

            for (int i = 1; i < str.Length; i++)
            {
                if (char.IsUpper(str[i]))
                {
                    result.Append('_');
                    result.Append(char.ToLower(str[i]));
                }
                else
                {
                    result.Append(str[i]);
                }
            }

            return result.ToString();
        }


        //// 辅助工具：将 PascalCase 转为 SNAKE_CASE
        //public static string ToSnakeCase(this string text) =>
        //    string.Concat(text.Select((x, i) => i > 0 && char.IsUpper(x) ? "_" + x : x.ToString()));

        //// 在导出 Widget 时调用
        //public static void ExportWidgetEvents(SglWidgetData data, StringBuilder sb)
        //{
        //    if (data.Events.Count == 0) return;

        //    // 注册总的回调
        //    sb.AppendLine($"    sgl_obj_set_event_cb({data.Id}, {data.EventCallbackName}, NULL);");

        //    // 2. 生成回调函数体
        //    StringBuilder funcBody = new StringBuilder();
        //    funcBody.AppendLine($"void {data.EventCallbackName}(sgl_obj_t* obj, sgl_event_t event, void* user_data) {{");

        //    foreach (var evItem in data.Events)
        //    {
        //        // 匹配触发器
        //        string sglEvent = $"SGL_EVENT_{evItem.Trigger.ToString().ToUpper()}";
        //        funcBody.AppendLine($"    if (event == {sglEvent}) {{");

        //        // 遍历该触发器下的所有动作
        //        foreach (var action in evItem.Actions)
        //        {
        //            switch (action.Type)
        //            {
        //                case SglActionType.ChangeScreen:
        //                    funcBody.AppendLine($"        ui_scr_load({action.TargetId});");
        //                    break;
        //                case SglActionType.SetProperty:
        //                    // 假设底层有对应的 set 函数
        //                    funcBody.AppendLine($"        ui_property_set_{action.AttrType}({action.TargetId}, {action.Value});");
        //                    break;
        //                case SglActionType.CallFunction:
        //                    funcBody.AppendLine($"        {action.Value}();");
        //                    break;
        //            }
        //        }
        //        funcBody.AppendLine("    }");
        //    }



        //}

        // --- 核心转换逻辑：RGB888 (WPF) -> RGB565 (Embedded) ---
        private static string sgl_rgb(Color c)
        {
            //// R: 取高 5 位 (8位右移3位)
            //// G: 取高 6 位 (8位右移2位)
            //// B: 取高 5 位 (8位右移3位)
            //ushort r = (ushort)((c.R >> 3) & 0x1F);
            //ushort g = (ushort)((c.G >> 2) & 0x3F);
            //ushort b = (ushort)((c.B >> 3) & 0x1F);

            //// 拼接：RRRRR GGGGGG BBBBB
            //int rgb565 = (r << 11) | (g << 5) | b;

            // 关键点：不再直接返回 0xFFFF，而是返回 sgl_color_make16(0xFFFF)
            // 这样 C 语言编译器就会识别为 sgl_color16_t 类型
            return $"sgl_rgb(0x{c.R:X2}, 0x{c.G:X2}, 0x{c.B:X2})";
        }

        // 对齐枚举名映射 (sgl_align_type_t)
        private static readonly string[] AlignEnumNames = new string[]
        {
            "SGL_ALIGN_CENTER",      // 0
            "SGL_ALIGN_TOP_MID",     // 1
            "SGL_ALIGN_TOP_LEFT",    // 2
            "SGL_ALIGN_TOP_RIGHT",   // 3
            "SGL_ALIGN_BOT_MID",     // 4
            "SGL_ALIGN_BOT_LEFT",    // 5
            "SGL_ALIGN_BOT_RIGHT",   // 6
            "SGL_ALIGN_LEFT_MID",    // 7
            "SGL_ALIGN_RIGHT_MID",   // 8
            "SGL_ALIGN_VERT_LEFT",   // 9
            "SGL_ALIGN_VERT_RIGHT",  // 10
            "SGL_ALIGN_VERT_MID",    // 11
            "SGL_ALIGN_HORIZ_TOP",   // 12
            "SGL_ALIGN_HORIZ_BOT",   // 13
            "SGL_ALIGN_HORIZ_MID",   // 14
        };

        private static string GetAlignEnumName(int alignIndex)
        {
            if (alignIndex >= 0 && alignIndex < AlignEnumNames.Length)
                return AlignEnumNames[alignIndex];
            return $"SGL_ALIGN_CENTER /* invalid:{alignIndex} */";
        }

        private static string EscapeCString(string text)
        {
            if (string.IsNullOrEmpty(text)) return string.Empty;

            return text
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }


    }






    public partial class MainWindow
    {
        private void ExportCode_Click(object sender, RoutedEventArgs e)
        {
            var screenList = SglScreen.Instance.ScreenList;
            if (screenList == null || !screenList.Any())
            {
                MessageBox.Show("没有可导出的屏幕内容");
                return;
            }

            // 选择导出文件夹
            // 注意：OpenFolderDialog 需要 .NET 8 或更高版本。
            // 如果是旧版本，请改用 Microsoft.Win32.SaveFileDialog 并诱导用户选文件夹


            string exportPath = ProjectManager.Instance.ExportFolder;


            if (string.IsNullOrEmpty(exportPath) || !Directory.Exists(exportPath))
            {
                var dialog = new CommonOpenFileDialog();
                dialog.IsFolderPicker = true; // 设置为文件夹选择模式
                                              //dialog.InitialDirectory = AppDomain.CurrentDomain.BaseDirectory;

                dialog.Title = "选择代码导出目录";

                if (dialog.ShowDialog() == CommonFileDialogResult.Ok)
                {

                    exportPath = dialog.FileName;
                    ProjectManager.Instance.ExportFolder = exportPath;
                }
                else
                {
                    return;
                }
            }


            //清空目录内容
            //ClearDirectorySafe(exportPath);


            // 创建子目录结构
            string fontDir = Path.Combine(exportPath, "fonts");
            string imgDir = Path.Combine(exportPath, "images");
            string screenDir = Path.Combine(exportPath, "screens");

            Directory.CreateDirectory(fontDir);
            Directory.CreateDirectory(imgDir);
            Directory.CreateDirectory(screenDir);





            // 递归获取所有控件（防止嵌套在 Panel 里的图片被漏掉）
            var list = new List<SglWidgetData>();

            List<SglWidgetData> GetFlattenWidgets(IEnumerable<SglWidgetData> ws)
            {

                foreach (var w in ws)
                {
                    list.Add(w);
                    if (w.Children.Count > 0) list.AddRange(GetFlattenWidgets(w.Children));
                }
                return list;
            }
            // 2. 导出所有图片 (images/)
            IEnumerable<SglWidgetData> imageWidgets = null;

            foreach (var screen in SglScreen.Instance.ScreenList)
            {
                var allWidgets = screen.Widgets;
                var flatWidgets = GetFlattenWidgets(allWidgets);
                imageWidgets = flatWidgets.Where(w => w is SglIconData || w is SglExtImageData || w is SglCircleData || w is SglPanelData).ToList();
            }

            HashSet<string> exportedFiles = new HashSet<string>();

            if (imageWidgets != null)
            {
                foreach (var widget in imageWidgets)
                {
                    string resName = "";
                    string prefix = "";

                    // 根据类型确定前缀和资源名
                    if (widget is SglIconData icon)
                    {
                        resName = icon.IconName;
                        prefix = "ico_" + widget.Id; // 图标前缀
                    }
                    else if (widget is SglExtImageData img)
                    {
                        resName = img.PixmapVarName;
                        prefix = "img_" + widget.Id; ; // 图片前缀
                    }
                    else if (widget is SglPanelData bg)
                    {
                        resName = bg.PixmapVarName;
                        prefix = "img_" + widget.Id; ; // 图片前缀
                    }
                    else if (widget is SglCircleData ciccle)
                    {
                        resName = ciccle.PixmapVarName;
                        prefix = "img_" + widget.Id; ; // 图片前缀
                    }

                    if (string.IsNullOrEmpty(resName)) continue;

                    // 资源查找逻辑 (保持不变)
                    var resItem = SglResManager.Resources.FirstOrDefault(r =>
                        r.Name.Equals(resName, StringComparison.OrdinalIgnoreCase));

                    if (resItem == null)
                    {
                        string pureName = Path.GetFileNameWithoutExtension(resName);
                        resItem = SglResManager.Resources.FirstOrDefault(r =>
                            r.Name.Equals(pureName, StringComparison.OrdinalIgnoreCase));
                    }

                    if (resItem == null) continue;

                    // --- 核心修改：生成带前缀的新名称 ---
                    string finalVarName = $"{prefix}_{resItem.Name}";

                    if (exportedFiles.Contains(finalVarName)) continue;

                    //int targetW = (int)widget.W;
                    //int targetH = (int)widget.H;
                    string format = ProjectManager.Instance.ColorFormat.ToString();

                    string code = $"// Error: File not found {resItem.FilePath}";

                    //if (!File.Exists(res.FilePath)) return $"// Error: File not found {res.FilePath}";


                    BitmapImage sourceBmp = SglImageGenerator.LoadBitmapNoLock(resItem.FilePath);

                    // 强制转为 Bgra32
                    var bgraBmp = new FormatConvertedBitmap(sourceBmp, PixelFormats.Bgra32, null, 0);

                    // 缩放
                    ScaleTransform scale = new ScaleTransform((double)widget.W / bgraBmp.PixelWidth, (double)widget.H / bgraBmp.PixelHeight);
                    Console.WriteLine($"{bgraBmp.PixelWidth} {bgraBmp.PixelHeight} {scale.Value}");
                    TransformedBitmap scaledBmp = new TransformedBitmap(bgraBmp, scale);
                    //高质量采样 导出
                    RenderOptions.SetBitmapScalingMode(scaledBmp, BitmapScalingMode.HighQuality);
                    if (widget is not SglIconData)
                    {

                        code = SglImageGenerator.ConvertToSglPixmapCode(scaledBmp, finalVarName.Substring(4), format);
                    }
                    else
                    {
                        code = SglImageGenerator.ConvertToSgl4BitIconCode(scaledBmp, finalVarName.Substring(4));
                    }


                    string outPath = Path.Combine(imgDir, $"{finalVarName.Substring(4)}.c");
                    File.WriteAllText(outPath, code);
                    exportedFiles.Add(finalVarName);
                }
            }

            //  导出字体 (fonts/)
            //var fontRes = SglResManager.Resources.Where(r => r.ResType == SglResType.FontCSource);
            //foreach (var res in fontRes)
            //{
            //    File.WriteAllText(Path.Combine(fontDir, $"{res.Name}.c"), res.GeneratedCode);
            //}
            //  导出字体 (直接从 assets 复制)
            var fontRes = SglResManager.Resources.Where(r => r.ResType == SglResType.FontCSource);
            foreach (var res in fontRes)
            {
                // 获取当前工程下的 assets 字体路径
                string path = AppDomain.CurrentDomain.BaseDirectory;
                string sourceFilePath = path = Path.Combine(ProjectManager.ProjectDir, res.FilePath); ;

                if (string.IsNullOrEmpty(sourceFilePath) || !File.Exists(sourceFilePath))
                {
                    Console.WriteLine("警告: 找不到字体取模文件, 跳过复制。");
                    continue;
                }

                // 目标路径：导出目录/fonts/文件名
                string fileName = Path.GetFileName(sourceFilePath);
                string destFilePath = Path.Combine(fontDir, fileName);

                try
                {
                    // 执行复制（true 表示覆盖同名文件）
                    File.Copy(sourceFilePath, destFilePath, true);
                    Console.WriteLine($"已导出字体: {fileName}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"导出字体 {res.Name} 失败: {ex.Message}");
                }
            }

            //  导出屏幕 (screens/)
            List<string> screenNames = new List<string>();

            try
            {

                //foreach (var screen in SglScreen.Instance.ScreenList)
                {

                    // 2. 遍历并导出每个屏幕的 .c 文件
                    foreach (var page in screenList)
                    {
                        string fileName = $"{page.Id}.c";
                        string fullPath = System.IO.Path.Combine(screenDir, fileName);

                        // 调用的代码生成逻辑
                        string cCode = SglMapping.ConvertPageToCode(page);
                        System.IO.File.WriteAllText(fullPath, cCode);

                        screenNames.Add(page.Id);
                    }

                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"导出失败: {ex.Message}", "错误", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            //导出事件
            StringBuilder sbEvent = new StringBuilder();
            sbEvent.AppendLine("/* SGL Auto Generated Events */");
            sbEvent.AppendLine("#include \"ui.h\"\n");

            foreach (var screen in SglScreen.Instance.ScreenList)
            {
                // 遍历每个屏幕的控件树生成函数体
                foreach (var widget in screen.Widgets)
                {
                    sbEvent.Append(SglMapping.GenerateCEventHandlers(widget, new HashSet<string>()));
                }
            }

            File.WriteAllText(Path.Combine(exportPath, "event.c"), sbEvent.ToString());

            string headerContent = SglMapping.GenerateHeaderFile(screenNames, SglResManager.Resources, exportedFiles);
            File.WriteAllText(Path.Combine(exportPath, "ui.h"), headerContent);
            string defineContent = SglMapping.GenerateDefineFile(screenNames, SglResManager.Resources, exportedFiles);
            File.WriteAllText(Path.Combine(exportPath, "ui.c"), defineContent);
            string helperContent = SglMapping.GenerateHelperFile(screenNames, SglResManager.Resources, exportedFiles);
            File.WriteAllText(Path.Combine(exportPath, "helper.c"), helperContent);


            MessageBox.Show($"导出完成！共生成 {screenList.Count} 个屏幕文件和 1 个头文件。",
                                   "导出成功", MessageBoxButton.OK, MessageBoxImage.Information);

        }


    }

}
